name: 'Login to Azure'
description: 'Install azure cli and login to Azure'

inputs:
  client_id:
    required: true
    description: Azure client id
  client_secret:
    required: true
    description: Azure client secret
  subscription_id:
    required: true
    description: Azure subscription id
  tenant_id:
    required: true
    description: Azure tenant id

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ inputs.client_id }}","clientSecret":"${{ inputs.client_secret }}","subscriptionId":"${{ inputs.subscription_id }}","tenantId":"${{ inputs.tenant_id }}"}'
